"""Draw the landing page's table plates from the committed fixtures.

    python fixtures/make_plates.py

Every plate under `frontend/public/assets/` is generated by this and by nothing
else. They are the only imagery on the marketing site, and the reason they can
be there at all is that each one is a real table out of `fixtures/papers/`
rather than an illustration of one: a product whose whole claim is that it
publishes nothing it cannot support cannot put a stock photograph on its own
front page.

A plate is one table reduced to its structure and nothing else. One mark per
real cell, the header band, a rule wherever the block index changes, the
genuinely bold cells in ink, the spacer column drawn as the gap it is, and
nothing at all where a cell is empty — because an empty cell means "not
reported" and never zero. No text, no axis, no legend: at card size the shape of
a table is the only thing that reads, and the shape is real.

Reads:
  frontend/src/fixtures/reports/*.json     parsed table structure
  fixtures/papers/1706.03762/results.tex   the source for the hero's left window

Writes:
  frontend/public/assets/bubble-source.svg      hero, left of the headline
  frontend/public/assets/bubble-structure.svg   hero, right of the headline
  frontend/public/assets/plate-*.svg            the showcase card row

Consumed by `frontend/src/components/site/bubbles.tsx` and `showcase.tsx`. The
showcase pairs each plate with its table by label and fails the build if a label
stops resolving, so a plate that goes stale stops the build rather than shipping
a picture of a table that is no longer there.
"""

import json
import pathlib
import re
import xml.sax.saxutils as sx

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "frontend" / "public" / "assets"

# 4:3, matching the template's 148x113 window (1.31) rounded to a clean ratio.
W, H = 320, 240

INK = "#111111"
GRID_NUM = "#d2d2d2"
GRID_TEXT = "#e8e8e8"
HEADER = "#c4c4c4"
RULE = "#111111"
HAIR = "#00000026"


def load_table(report: str, label: str):
    d = json.loads((ROOT / "frontend/src/fixtures/reports" / report).read_text("utf8"))
    for t in d["tables"]:
        if t.get("label") == label and not t.get("is_nested"):
            return t
    raise SystemExit(f"no table {label} in {report}")


def structure_plate(table) -> str:
    """The table reduced to its structure. No text: every mark is a real cell."""
    cells = table["cells"]
    n_rows = max(c["row"] for c in cells) + 1
    n_cols = max(c["col"] for c in cells) + 1

    pad_x, pad_y = 26, 30
    gw, gh = W - 2 * pad_x, H - 2 * pad_y
    gap = 2.0
    cw = (gw - gap * (n_cols - 1)) / n_cols
    ch = (gh - gap * (n_rows - 1)) / n_rows

    # A column whose every cell is empty is the spacer column: column index and
    # cell index part company there, which is the hazard the plate is showing.
    spacers = {
        c for c in range(n_cols)
        if all(not (x["text"] or "").strip() for x in cells if x["col"] == c)
    }

    by_row_block = {}
    for c in cells:
        by_row_block.setdefault(c["row"], c["block"])

    parts = [f'<rect width="{W}" height="{H}" fill="#ffffff"/>']

    # \toprule and \bottomrule.
    parts.append(
        f'<rect x="{pad_x}" y="{pad_y - 7:.1f}" width="{gw}" height="1.4" fill="{RULE}"/>'
    )
    parts.append(
        f'<rect x="{pad_x}" y="{pad_y + gh + 5.6:.1f}" width="{gw}" height="1.4" fill="{RULE}"/>'
    )

    for c in cells:
        if c["col"] in spacers:
            continue
        x = pad_x + c["col"] * (cw + gap)
        y = pad_y + c["row"] * (ch + gap)
        text = (c["text"] or "").strip()
        if c["is_bold"]:
            fill = INK
        elif c["is_header"]:
            fill = HEADER
        elif not text:
            continue  # empty means "not reported", never zero
        elif c.get("value") is not None or c.get("values"):
            fill = GRID_NUM
        else:
            fill = GRID_TEXT
        parts.append(
            f'<rect x="{x:.1f}" y="{y:.1f}" width="{cw:.1f}" height="{ch:.1f}" '
            f'rx="0.8" fill="{fill}"/>'
        )

    # The spacer column, drawn as the gap it is.
    for c in sorted(spacers):
        x = pad_x + c * (cw + gap) + cw / 2
        parts.append(
            f'<line x1="{x:.1f}" y1="{pad_y:.1f}" x2="{x:.1f}" y2="{pad_y + gh:.1f}" '
            f'stroke="{HAIR}" stroke-width="1" stroke-dasharray="2 3"/>'
        )

    # A rule wherever the block index changes: \midrule, \hline, \specialrule.
    prev = None
    for r in range(n_rows):
        blk = by_row_block.get(r)
        if prev is not None and blk != prev:
            y = pad_y + r * (ch + gap) - gap / 2
            parts.append(
                f'<rect x="{pad_x}" y="{y:.1f}" width="{gw}" height="1" fill="{RULE}"/>'
            )
        prev = blk

    return svg(parts)


SOURCE_LINES = 9

# The crop starts at the \hline opening the ensembles block, because those nine
# lines carry every hazard the parser has to survive at once: \textbf and
# \boldmath as two different spellings of bold, \specialrule segmenting the
# table into blocks, a \multicolumn that belongs to no single column, \rule
# spacing junk glued to cell content, \citep inside a label cell, scientific
# notation in math mode, and the empty spacer column as a bare `& &`.
SOURCE_ANCHOR = "Deep-Att + PosUnk Ensemble"


def source_plate(tex: pathlib.Path) -> str:
    """The same table as it is written. Real source, verbatim, from the tarball."""
    raw = tex.read_text("utf8").splitlines()
    start = next(i for i, ln in enumerate(raw) if SOURCE_ANCHOR in ln) - 1
    lines = [ln.rstrip() for ln in raw[start : start + SOURCE_LINES]]

    pad_x, pad_y = 16, 20
    lh = (H - 2 * pad_y) / SOURCE_LINES
    size = 9.5

    parts = [f'<rect width="{W}" height="{H}" fill="#ffffff"/>']
    for i, ln in enumerate(lines):
        y = pad_y + i * lh + size
        # The commands the parser is actually looking for are set in ink; the
        # rest is the noise it has to read past.
        colour = INK if re.search(r"\\(textbf|boldmath|specialrule|hline)", ln) else "#9a9a9a"
        parts.append(
            f'<text x="{pad_x}" y="{y:.1f}" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" '
            f'font-size="{size}" fill="{colour}" xml:space="preserve">{sx.escape(ln[:46])}</text>'
        )
    return svg(parts)


def svg(parts) -> str:
    body = "\n  ".join(parts)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
        f'width="{W}" height="{H}" role="img">\n  {body}\n</svg>\n'
    )


# One table per paper, chosen for a different structural story each time rather
# than by a rule, because "most cells" picks CLIP's 2,010-cell monster twice over
# and "most bold" picks the same table the bubbles already carry. The choice of
# which real table to show is editorial; every mark drawn in it is not.
SHOWCASE = [
    # 17x7, eight rule-delimited blocks, and the only table here that carries
    # real parse warnings: two rows cover six columns against a spec of seven.
    ("plate-resnet-arch.svg", "1512.03385.json", "tab:arch"),
    # 12x6, four blocks, four bold, and the empty spacer column at index 3 that
    # makes column index and cell index part company.
    ("plate-transformer-wmt.svg", "1706.03762.json", "tab:wmt-results"),
    # 15x5, four blocks, eight bold.
    ("plate-bert-squad.svg", "1810.04805.json", "tab:squad_results"),
    # 13x14, the widest tractable table in the corpus.
    ("plate-clip-retrieval.svg", "2103.00020.json", "table:retrieval"),
]


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    t = load_table("1706.03762.json", "tab:wmt-results")
    (OUT / "bubble-structure.svg").write_text(structure_plate(t), "utf8")
    (OUT / "bubble-source.svg").write_text(
        source_plate(ROOT / "fixtures/papers/1706.03762/results.tex"), "utf8"
    )
    print("wrote bubble-structure.svg, bubble-source.svg")
    for name, report, label in SHOWCASE:
        p = OUT / name
        p.write_text(structure_plate(load_table(report, label)), "utf8")
        print(f"wrote {name:<30} {label:<26} {p.stat().st_size:>6} bytes")
